# APLICACIONES EN CIENCIAS DE COMPUTACION

## Laboratorio 1: Definicion de Problema de Busqueda de Rutas

La tarea de este laboratorio consiste en definir el problema de busqueda de rutas entre dos puntos en un mapa dado. Especificamente se pide implementar la clase MapSearchProblem, que es una subclase de la clase genérica Problem. El constructor de MapSearchProblem recibe: la ciudad inicial (initial), la ciudad donde se quiere llegar (goal) y un mapa. Abajo puede encontrar la definición de la clase Problem y la clase que tiene que implementar MapSearchProblem. Hay que implementar los métodos indicados con #TODO. 

El mapa es un diccionario, cada entrada almacena las ciudades vecinas de una ciudad y los respectivos costos (distancias) para acanzarlas. Un ejemplo de la estructura mapa es mostrado abajo para el mapa de Romania

<b> Clase genérica Problem (no modificar) </b>

In [8]:
class Problem(object):
    def __init__(self, initial, goal=None):
        """Este constructor especifica el estado inicial y posiblemente el estado(s) objetivo(s),
        La subclase puede añadir mas argumentos."""
        self.initial = initial
        self.goal = goal

    def actions(self, state):
        """Retorna las acciones que pueden ser ejecutadas en el estado dado.
        El resultado es tipicamente una lista."""
        raise NotImplementedError

    def result(self, state, action):
        """Retorna el estado que resulta de ejecutar la accion dada en el estado state.
        La accion debe ser alguna de self.actions(state)."""
        raise NotImplementedError

    def goal_test(self, state):
        """Retorna True si el estado pasado satisface el objetivo."""
        raise NotImplementedError

    def path_cost(self, c, state1, action, state2):
        """Retorna el costo del camino de state2 viniendo de state1 con 
        la accion action, asumiendo un costo c para llegar hasta state1. 
        El metodo por defecto cuesta 1 para cada paso en el camino."""
        return c + 1

    def value(self, state):
        """En problemas de optimizacion, cada estado tiene un valor. Algoritmos
        como Hill-climbing intentan maximizar este valor."""
        raise NotImplementedError

<b> Clase a implementar </b>

In [23]:
class MapSearchProblem(Problem):
    def __init__(self, initial, goal, mapa):
        """El constructor recibe  el estado inicial, el estado objetivo y un mapa"""
        self.initial = initial
        self.goal = goal
        self.map = mapa

    def actions(self, state):
        """Retorna las acciones ejecutables desde ciudad state.
        El resultado es una lista de strings tipo 'goCity'. 
        Por ejemplo, en el mapa de Romania, las acciones desde Arad serian:
         ['goZerind', 'goTimisoara', 'goSibiu']"""
        #TODO
        
        ciudadesCercanas= self.map[state] #[(Z,12,12),(T,451),(S,12)]
        self.actio=['go'+ i for i,j in ciudadesCercanas]  
        return self.actio
        raise NotImplementedError
      

    def result(self, state, action):
        """Retorna el estado que resulta de ejecutar la accion dada desde ciudad state.
        La accion debe ser alguna de self.actions(state)
        Por ejemplo, en el mapa de Romania, el resultado de aplicar la accion 'goZerind' 
        desde el estado 'Arad' seria 'Zerind'"""  
        #TODO
        for act in self.actions(state):
            if act==action:
                #act= goCity
                #act[2:]=City
                self.state=act[2:]  
        return self.state        
        raise NotImplementedError
        
    def goal_test(self, state):
        """Retorna True si state es self.goal"""
        #TODO       
        return state==self.goal
        raise NotImplementedError

    def path_cost(self, c, state1, action, state2):
        """Retorna el costo del camino de state2 viniendo de state1 con la accion action 
        El costo del camino para llegar a state1 es c. El costo de la accion debe ser
        extraido de self.map."""
        #TODO
        costo=0
        ciudadesCercanas= self.map[state1]
        estadosPosibles=[i for i,j in ciudadesCercanas] #[Z,T,S]
        costosPosibles= [j for i,j in ciudadesCercanas] #[75,118,140]
        a=0 #índice de iteración
        for estado in estadosPosibles:
            if estado==state2:
                costo=costosPosibles[a]
                break
            a=a+1                    
        self.cost=costo+c
        return self.cost
        raise NotImplementedError

<b> Mapa de Romania de ejemplo para pruebas (las ciudades estan identificadas con su letra inicial) </b>

In [10]:
romania = {
 'A': [('Z',75), ('T',118), ('S',140)],
 'B': [('F',211), ('P',101), ('G',90), ('U',85)],
 'C': [('D',120), ('R',146), ('P',138)],
 'D': [('M',75), ('C',120)],
 'E': [('H',86)],
 'F': [('S',99), ('B',211)],
 'G': [('B',90)],
 'H': [('U',98), ('E',86)],
 'I': [('N',87), ('V',92)],
 'L': [('T',111), ('M',70)],
 'M': [('L',70), ('D',75)],
 'N': [('I',87)],
 'O': [('Z',71), ('S',151)],
 'P': [('R',97), ('C',138), ('B',101)],
 'R': [('S',80), ('C',146), ('P',97)],
 'S': [('A',140), ('O',151), ('F',99), ('R',80)],
 'T': [('A',118), ('L',111)],
 'U': [('B',85), ('V',142), ('H',98)],
 'V': [('U',142), ('I',92)],
 'Z': [('O',71), ('A',75)]}

por ejemplo, para extraer las ciudades vecinas a 'A', tipear

In [31]:
romania['A']

[('Z', 75), ('T', 118), ('S', 140)]

dará una lista de tres tuplas: [('Z', 75), ('T', 118), ('S', 140)] , cada tupla conteniendo la ciudad y el costo para llegar desde 'A'

<b> Probar la implementacion haciendo Busquedas con GraphSearch </b>

La clase implementada debera ser testada, instanciando un problema específico de busqueda. Para ello usaremos el mapa de Romania y la ciudad 'A' como inicio y 'B' como objetivo:  

In [33]:
romania_problem = MapSearchProblem('A', 'B', romania)

Una vez instanciado el problema, correr el algoritmo de busqueda graph_search(), pasando como problema romania_problem y como frontera una lista FIFO (Busqueda en amplitud) y una lista tipo pila (Busqueda en profundidad). La implementacion de GraphSearch, lista FIFO y la clase Node (necesaria para GraphSearch) es dada a seguir:      

In [35]:
class Node:
    def __init__(self, state, parent=None, action=None, path_cost=0):
        "Crea un nodo de arbol de busqueda, derivado del nodo parent y accion action"
        self.state = state
        self.parent = parent
        self.action = action
        self.path_cost = path_cost
        self.depth = 0
        if parent:
            self.depth = parent.depth + 1

    def expand(self, problem):
        "Devuelve los nodos alcanzables en un paso a partir de este nodo."
        return [self.child_node(problem, action)
                for action in problem.actions(self.state)]

    def child_node(self, problem, action):
        next = problem.result(self.state, action)
        return Node(next, self, action,
                    problem.path_cost(self.path_cost, self.state, action, next))

    def solution(self):
        "Retorna la secuencia de acciones para ir de la raiz a este nodo."
        return [node.action for node in self.path()[1:]]

    def path(self):
        "Retorna una lista de nodos formando un camino de la raiz a este nodo."
        node, path_back = self, []
        while node:
            path_back.append(node)
            node = node.parent
        return list(reversed(path_back))

In [36]:
def graph_search(problem, frontier):
    frontier.append(Node(problem.initial))
    explored = set()
    while frontier:
        node = frontier.pop()
        if problem.goal_test(node.state):
            return node
        explored.add(node.state)
        frontier.extend(child for child in node.expand(problem)
                        if child.state not in explored and
                        child not in frontier)
    return None

In [37]:
from collections import deque

class FIFOQueue(deque):
    """Una cola First-In-First-Out"""
    def pop(self):
        return self.popleft()

<b> Ejecutar la busqueda en romania_problem </b>

Con estas definiciones ya puede ejecutar la busqueda para nuestro problema romania_problem.

Ejecutar busqueda en Amplitud  

In [43]:
node_solucionBFS = graph_search(romania_problem, FIFOQueue())
solucionBFS = node_solucionBFS.solution()
print(solucionBFS)

['goS', 'goF', 'goB']


Ejecutar busqueda en Profundidad 

In [44]:
node_solucionDFS =graph_search(romania_problem, [])  # una lista [] es una pila en Python
solucionDFS = node_solucionDFS.solution()
print (solucionDFS)

['goS', 'goR', 'goP', 'goB']
